config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#top'
  resources :users
  resources :post_images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :post_images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new

  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
    @post_images = PostImage.all
  end

  def show
  end

  def destroy
  end

  private

  def post_image_params
    params.require(:post_image).permit(:book_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def top
  end

  def index
    @users = User.all
  end

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div id="sp-menu">
      <h2 class="mt-3">MENU</h2>
      <ul class="nav navbar bg-dark ml-auto">
        <% if user_signed_in? %>
        <li><%= link_to " Home", root_path, class: "fas fa-home text-light" %></li>
        <li><%= link_to " Users", users_path, class: "fas fa-users text-light" %></li>
        <li><%= link_to " Books", post_images_path, class: "fas fa-book-open text-light" %></li>
        <li><%= link_to " Post", new_post_image_path, class: "fas fa-feather-alt text-light" %></li>
        <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-hiking text-light" %></li>
        <% else %>
        <li><%= link_to " Home", root_path, class: "fas fa-home text-light" %></li>
        <li><%= link_to " About", root_path, class: "fas fa-link text-light" %></li>
        <li><%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus text-light" %></li>
        <li><%= link_to " login", new_user_session_path, class: "fas fa-key text-light" %></li>
        <% end %>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
  </header>
  <main>
  <p><%= flash[:notice] %></p>
  </main>
  <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/post_images/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <h3>User Info</h3>
      <h4>image</h4>
      <table class="table">
        <tr>
          <th>Name</th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th>Introduction</th>
          <td><%= current_user.introduction %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-9 text-center">
      <h1>Books</h1>
        <table class="table table-hover">
          <thead class="thead thead-dark">
            <tr>
              <th>user.name</th>
              <th>image</th>
              <th>book_name</th>
              <th>caption</th>
            </tr>
          </thead>
          <% @post_images.each do |post_image| %>
          <tbody>
            <tr>
              <td>user.image<br><%= current_user.name %></td>
              <td>user.image</td>
              <td><%= post_image.book_name %></td>
              <td>caption</td>
            </tr>
          </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="container text-center">
  <div class="row ustify-content-center">
    <div class="col alert alert-primary">
      <h2 class="mt-2">画像投稿フォーム</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mt-5">
      <div class="card" style="width: 25rem;">
        <img class="card-img-top img-fluid" src="https://picsum.photos/300/200">
        <div class="card-body">
          <%= form_with model: @post_image, local:true do |f| %>
          <h5 class="card-title">画像</h5>
          <p class="card-text"><%= f.attachment_field :image %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-5">
      <h5>ブックタイトル</h5>
      <%= f.text_field :book_name %>
      <h5>説明</h5>
      <%= f.text_area :caption %>
      <p><%= f.submit '投稿', class: 'btn btn-primary' %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">

      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60 fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <th>name</th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= current_user.introduction %></td>
        </tr>
      </table>


    </div>
    <div class="col-md-9">
      <% @users.each do |user| %>
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>user.image</th>
            <th>name</th>
            <th></th>
            <th>caption</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>image</td>
            <td><%= user.name %></td>
            <th><%= user.introduction %></th>
            <td></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>image</h3>
<%= current_user.name %>
<%= current_user.introduction %>

<%# @user.each do |user| %>
  <table>
    <tr>
      <th>image</th>
      <th>user.name</th>
      <th>user.introduction</th>
    </tr>
    <tr>
      <td>image</td>
      <td>user.name</td>
      <td>user.introduction</td>
    </tr>
  </table>
<%# end %>

app/views/users/top.html.erb
<h1>トップページ</h1>